### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by icamys** [bibby/radula#12]
After installing the latest version of package (0.8.1) getting weird error. Here's full list of commands:

```
$ sudo pip3.6 install -Iv https://github.com/bibby/radula/archive/v0.8.1.tar.gz
# ...

$ which radula
/usr/local/bin/radula

$ python3.6 /usr/local/bin/radula --version
Traceback (most recent call last):
  File "/usr/local/bin/radula", line 11, in <module>
    load_entry_point('radula==0.8.1', 'console_scripts', 'radula')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/radula/__init__.py", line 50
    print __version__
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print __version__)?
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/radula", line 11, in <module>
    load_entry_point('radula==0.8.1', 'console_scripts', 'radula')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/radula/__init__.py", line 50
    print __version__
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print __version__)?
```

**Comment by bibby** [comment]
I confess that radula is developed with python 2.7 as a target platform (shame on us).
Urgency is increasing to modernize the package.
