### ISSUE TITLE
.boto configuration

### ISSUE THREAD

**Issue by bibby** [bibby/radula#3]
## The following is an email exchange with ghislain.chevalier {at} orange {dot} com

Hi,

I want to test radula on my sandbox

I currenty use s3cmd so I picked the parameters in .cfg file to build /etc/boto.cfg

```
[s3]
host = v-sbceph11

[Boto]
is_secure = False
debug = 2
proxy = proxy
proxy_port = 8080

[Credentials]
aws_access_key_id = [redacted]
aws_secret_access_key = [redeacted]
```

When I launch radula lb I got the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/radula", line 9, in <module>
    load_entry_point('radula==0.4.4', 'console_scripts', 'radula')()
  File "/usr/local/lib/python2.7/dist-packages/radula-0.4.4-py2.7.egg/radula/__init__.py", line 158, in main
    _real_main()
  File "/usr/local/lib/python2.7/dist-packages/radula-0.4.4-py2.7.egg/radula/__init__.py", line 64, in _real_main
    getattr(radu, command)(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/radula-0.4.4-py2.7.egg/radula/proxy.py", line 37, in lb
    self.list_buckets(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/radula-0.4.4-py2.7.egg/radula/proxy.py", line 41, in list_buckets
    for bucket_name in sorted([bucket.name for bucket in self.lib.get_buckets()]):
  File "/usr/local/lib/python2.7/dist-packages/radula-0.4.4-py2.7.egg/radula/rad.py", line 328, in get_buckets
    return self.conn.get_all_buckets()
  File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 345, in get_all_buckets
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>[redacted]</AWSAccessKeyId><RequestId>redactes</RequestId><HostId>[redacted]</HostId></Error>
```

Do I miss something in the configuration file? (it looks like a standard AWS error message)

Best regards

**Comment by bibby** [comment]
Hello, ghislain.
The boto config looks to be correct, so it makes me wonder if its loading at all. You see, with `debug = 2`, additional httplib2 debug should appear as well allowing visual confirmation of the target host.

Boto configuration loads /etc/boto.cfg first, then other files may override its settings.
See if your system has present any of these with content that could conflict:
- $HOME/.aws/credentials
- $HOME/.boto

Also test if there are these environment variables in play, as they will have the final say in all configuration:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_PROFILE

These sneaky env vars have been the primary source of connection problems that I'm aware of.

I'd start there. Let me know if it works out.
radula 0.4.4 is the current version we use at work regularly, and with similar config files to yours.

I hope this solves it for you.
Best regards.

**Comment by bibby** [comment]
Closed for inactivity
